Fastlz update
RT-Thread-packages/fastlz pull request #1
Opened 2018-02-11 09:05 UTC by zhaojuntao

1.  增加例程   
2.  增加 readme

2018-02-11 11:11 UTC, BernardXiong commented on README.md
> +  menuconfig package path：`RT-Thread online package` -> `miscellaneous package` -> `Fastlz`
获取方式这部分，不建议直接再给出 `git clone ...git` 的模式，而是着重在menuconfig中怎么使能。

另外，未来有关于menuconfig的描述可以更类似这样：

    RT-Thread online packages --->
        miscellaneous packages --->
            [*] Fastlz

以前面4个空格方式代表下以及选择，同时 `[*]` 代表选择了这样的选项。（注意前面的选项是和menuconfig中是一致的。例如是`RT-Thread online packages`而不是`RT-Thread online package`）

2018-02-11 11:13 UTC, BernardXiong commented on README.md
> +  原因： FastLZ 代码中默认配置使用的内存空间比较大， 可能会超出 `msh` 线程的堆栈空间
如果这个栈空间需要到40960，这个本身就不是一个靠谱的例子了，请找出原因出来。

2018-02-11 11:14 UTC, BernardXiong commented on SConscript
> +Import('rtconfig')
请多多学习SConscript的写法。

1. Import('RTT_ROOT') 这类，如果在SConscript中并未用到RTT_ROOT变量，那么就不应该导入这个变量；
2. Import('rtconfig') 同上。

2018-02-11 11:16 UTC, BernardXiong commented on SConscript
> +group = DefineGroup('fastlz', src, depend = ['FASTLZ_USING_SAMPLE'], CPPPATH = CPPPATH)
请学习下，`python $RTT_ROOT/tools/wizard.py --component TestCom`产生的SConscript脚本，为什么是这样而不是其他。

我们需要保持代码简洁的初心（小而精练，整洁）。

2018-02-11 11:17 UTC, BernardXiong commented on fastlz_sample.c
> +MSH_CMD_EXPORT_ALIAS(fastlz_test, fastlz_test, fastlz compress and decompress test);
这里为什么使用MSH_CMD_EXPORT_ALIAS，而不是MSH_CMD_EXPORT？

2018-02-11 11:18 UTC, BernardXiong requested changes
Please change code according to the comments.

2018-02-13 03:26 UTC, armink requested changes

2018-02-13 03:26 UTC, armink commented on fastlz_sample.c
> +#define COMPRESS_BUFFER_PADDING        400
这个 buffer padding 是当时使用 quicklz 时， quicklz 强制要求的。检查下 fastlz 是否需要

2018-02-24 06:23 UTC, zhaojuntao commented on fastlz_sample.c
> +#define COMPRESS_BUFFER_PADDING        400
需要有5%的余量

The output buffer must be at least 5% larger than the input buffer

2018-02-24 06:23 UTC, zhaojuntao commented on fastlz_sample.c
> +MSH_CMD_EXPORT_ALIAS(fastlz_test, fastlz_test, fastlz compress and decompress test);
已经修改

2018-02-24 06:23 UTC, zhaojuntao commented on SConscript
> +group = DefineGroup('fastlz', src, depend = ['FASTLZ_USING_SAMPLE'], CPPPATH = CPPPATH)
已经修改，看下是否符合要求

2018-02-24 06:55 UTC, armink approved these changes

2018-02-24 08:11 UTC, merged